version: '3.3'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:80"

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app              
      - ./models:/app/models